//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class App {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Resources.App", typeof(App).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AttackFailed {
            get {
                return ResourceManager.GetString("AttackFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AttackSucceeded {
            get {
                return ResourceManager.GetString("AttackSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GuardsKilled {
            get {
                return ResourceManager.GetString("GuardsKilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MessageType_AlreadyHave {
            get {
                return ResourceManager.GetString("MessageType_AlreadyHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MessageType_AtkLevelIncreased {
            get {
                return ResourceManager.GetString("MessageType_AtkLevelIncreased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MessageType_AttackAttempted {
            get {
                return ResourceManager.GetString("MessageType_AttackAttempted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MessageType_BoughtIngredients {
            get {
                return ResourceManager.GetString("MessageType_BoughtIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MessageType_BoughtNewBuilding {
            get {
                return ResourceManager.GetString("MessageType_BoughtNewBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MessageType_ChosenLevelAboveMax {
            get {
                return ResourceManager.GetString("MessageType_ChosenLevelAboveMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MessageType_DefLevelIncreased {
            get {
                return ResourceManager.GetString("MessageType_DefLevelIncreased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MessageType_EducationIncreased {
            get {
                return ResourceManager.GetString("MessageType_EducationIncreased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MessageType_GotHired {
            get {
                return ResourceManager.GetString("MessageType_GotHired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MessageType_HiredGuards {
            get {
                return ResourceManager.GetString("MessageType_HiredGuards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MessageType_HiredMobsters {
            get {
                return ResourceManager.GetString("MessageType_HiredMobsters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MessageType_LevelAlreadyMaxed {
            get {
                return ResourceManager.GetString("MessageType_LevelAlreadyMaxed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MessageType_LevelCantBeReduced {
            get {
                return ResourceManager.GetString("MessageType_LevelCantBeReduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MessageType_MoonshineCantBeBought {
            get {
                return ResourceManager.GetString("MessageType_MoonshineCantBeBought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MessageType_MustBeNonNegative {
            get {
                return ResourceManager.GetString("MessageType_MustBeNonNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MessageType_MustBePositive {
            get {
                return ResourceManager.GetString("MessageType_MustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MessageType_NotEnoughEducation {
            get {
                return ResourceManager.GetString("MessageType_NotEnoughEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MessageType_NotEnoughFame {
            get {
                return ResourceManager.GetString("MessageType_NotEnoughFame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MessageType_NotEnoughFood {
            get {
                return ResourceManager.GetString("MessageType_NotEnoughFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MessageType_NotEnoughMobsters {
            get {
                return ResourceManager.GetString("MessageType_NotEnoughMobsters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MessageType_NotEnoughMoney {
            get {
                return ResourceManager.GetString("MessageType_NotEnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MessageType_NotEnoughMoves {
            get {
                return ResourceManager.GetString("MessageType_NotEnoughMoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MessageType_StopPlayingWithYourself {
            get {
                return ResourceManager.GetString("MessageType_StopPlayingWithYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MessageType_Todo {
            get {
                return ResourceManager.GetString("MessageType_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MessageType_WorldRestarted {
            get {
                return ResourceManager.GetString("MessageType_WorldRestarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MoneyStolen {
            get {
                return ResourceManager.GetString("MoneyStolen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor.
        /// </summary>
        internal static string Weapon_Armor {
            get {
                return ResourceManager.GetString("Weapon_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axe.
        /// </summary>
        internal static string Weapon_Axe {
            get {
                return ResourceManager.GetString("Weapon_Axe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bat.
        /// </summary>
        internal static string Weapon_Bat {
            get {
                return ResourceManager.GetString("Weapon_Bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knife.
        /// </summary>
        internal static string Weapon_Knife {
            get {
                return ResourceManager.GetString("Weapon_Knife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pistol.
        /// </summary>
        internal static string Weapon_Pistol {
            get {
                return ResourceManager.GetString("Weapon_Pistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzi.
        /// </summary>
        internal static string Weapon_Uzi {
            get {
                return ResourceManager.GetString("Weapon_Uzi", resourceCulture);
            }
        }
    }
}
